[project]
name = "web-scrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.15.0",
    "python-dotenv>=1.1.1",
    "scrapy>=2.13.3",
]
